apiVersion: v1
kind: Service
metadata:
  name: first-app-service  # Specifies the name of the Service.
spec:
  selector:
    app: first-app  # Selects Pods with the label "app: first-app".
  ports:
    - protocol: TCP  # Specifies the protocol (TCP or UDP) used by the ports.
      port: 80       # Specifies the port number on the Service.
      targetPort: 8080  # Specifies the port number on the Pods that traffic should be forwarded to.
  type: LoadBalancer  # Specifies the type of Service. LoadBalancer creates an external load balancer to expose the Service outside the cluster.
